openapi: 3.0.3
info:
  title: Messari Metrics
  description: Service providing metrics on single and aggregate assets from Messari Data.
  version: "1.0"
servers:
- url: http://localhost:8000/api/
paths:
  /aggregate:
    get:
      tags:
      - metrics
      summary: aggregate metrics
      operationId: metrics#aggregate
      parameters:
      - name: tag
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Et quasi omnis voluptas.
        example: Doloribus ut ducimus sit.
      - name: sector
        in: query
        allowEmptyValue: true
        schema:
          type: string
          example: Ipsa architecto perspiciatis dolorem.
        example: Pariatur esse voluptatem aliquid.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricsassetResponseBody'
                description: aggregated metrics
                example:
                - assetSlug: Earum reprehenderit aut quia et.
                  chg24hr: 0.22850602112513993
                  mktcap: 0.0441609119748389
                  price: 0.5800515509158537
                  vlm24hr: 0.8549848215992812
                - assetSlug: Earum reprehenderit aut quia et.
                  chg24hr: 0.22850602112513993
                  mktcap: 0.0441609119748389
                  price: 0.5800515509158537
                  vlm24hr: 0.8549848215992812
                - assetSlug: Earum reprehenderit aut quia et.
                  chg24hr: 0.22850602112513993
                  mktcap: 0.0441609119748389
                  price: 0.5800515509158537
                  vlm24hr: 0.8549848215992812
                - assetSlug: Earum reprehenderit aut quia et.
                  chg24hr: 0.22850602112513993
                  mktcap: 0.0441609119748389
                  price: 0.5800515509158537
                  vlm24hr: 0.8549848215992812
              example:
              - assetSlug: Earum reprehenderit aut quia et.
                chg24hr: 0.22850602112513993
                mktcap: 0.0441609119748389
                price: 0.5800515509158537
                vlm24hr: 0.8549848215992812
              - assetSlug: Earum reprehenderit aut quia et.
                chg24hr: 0.22850602112513993
                mktcap: 0.0441609119748389
                price: 0.5800515509158537
                vlm24hr: 0.8549848215992812
  /asset/{slug}:
    get:
      tags:
      - metrics
      summary: asset metrics
      operationId: metrics#asset
      parameters:
      - name: slug
        in: path
        required: true
        schema:
          type: string
          example: Ullam ratione et magnam cumque.
        example: Aut et qui aut fuga rerum.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsassetResponseBody'
              example:
                assetSlug: Eos veniam omnis asperiores sunt a velit.
                chg24hr: 0.3684056302495918
                mktcap: 0.6969528185978329
                price: 0.12177489652670526
                vlm24hr: 0.27326719988534426
components:
  schemas:
    MetricsassetResponseBody:
      $ref: '#/components/schemas/MetricsassetResponseBody'
